config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'

  root 'posts#index'
  resources :posts do
    resources :comments
  end

  devise_for :users, controllers: {registrations: 'registrations'}
  resources :questions

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  validates :content, presence: true, length: {minimum: 3, maximum: 150}
end

app/models/post.rb
class Post < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, use: :slugged

  belongs_to :user
  has_many :comments

  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :body, presence: true, length: {minimum: 3, maximum: 500}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  validates_attachment_file_name :avatar, matches: [/png\Z/, /jpe?g\Z/]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :admin])
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :avatar) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:name, :email, :password, :current_password) }
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.friendly.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    CommentMailer.comment_added(current_user, @post, @comment.content).deliver_later

    respond_to do |format|
      format.html { redirect_to post_path(@post) }
      format.js
    end
  end

  def destroy
    @post = Post.friendly.find(params[:post_id])
    @comment = @post.comments.find(params[:id]).destroy

    respond_to do |format|
      format.html { redirect_to post_path(@post) }
      format.js
    end    
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to posts_path
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @author_id = @post.user_id
    @author = User.find(@author_id)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @user = current_user
    @post = @user.posts.new(post_params)

    respond_to do |format|
      if @post.save

        PostMailer.post_created(@user, @post).deliver_later
        PostMailer.admin_notifier(@user, @post).deliver_later

        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
      format.js {render :layout => false}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id, :username)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div>
	<span class="date datetime text-muted"><%= time_ago_in_words(comment.created_at) %> ago</span>

	<p><%= comment.content %>
	<sup><%= link_to 'x', post_comment_path(comment.post, comment), method: :delete, :class => 'comment-destroy', remote: true, title: 'Delete' %></sup></p>

	<hr>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build], remote: true) do |f| %>
    <div class="field">
      <%= f.text_area :content, autofocus: true, placeholder: 'Your comment', class: 'form-control', style: 'width: 30%' %>
    </div>

    <div class="actions">
      <%= f.submit 'Post Comment', class: 'btn' %>
    </div>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/create.js.erb
$('#comments').append('<%= j render @comment %>');
$('#comment_content').val("");
$('#comments-count').text('(<%= @post.comments.count %>)');

app/views/comments/destroy.js.erb
$('.comment-destroy').bind('ajax:success', function() {
  $(this).closest('div').fadeOut();
  $('#comments-count').text('(<%= @post.comments.count %>)');
});

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:page_title) %> | CancanDemo</title>
  <%= favicon_link_tag('m.ico') %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
<div class="container">
    <% if current_user %>
        <p><%= link_to current_user.name, edit_user_registration_path %> | <%= link_to 'Log out', destroy_user_session_path, method: :delete %></p>
    <% end %>

    <!--<p class="notice"><%= notice %></p>-->
    <!--<p class="alert"><%= alert %></p>-->

    <%= yield %>
</div>


</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, autofocus: true, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :body %><br>
    <%= f.text_area :body, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>

  <div class="field form-group">
    <%= f.hidden_field :username, :value => current_user.name %>
  </div>

  <div class="field form-group">
    <%= submit_tag "Submit", class: 'btn btn-primary', data: { disable_with: "Please wait..." }%>
  </div>
<% end %>

app/views/posts/destroy.js.erb
$('.delete_post').bind('ajax:success', function() {
  $(this).closest('tr').fadeOut();
});

app/views/posts/edit.html.erb
<%= provide(:page_title, 'Edit Post') %>

<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= provide(:page_title, 'Main Page') %>

<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th style="text-align: center">Title</th>
      <th style="text-align: center">Body</th>
      <th style="text-align: center">Author</th>
      <th style="text-align: center">Comments</th>
      <th style="text-align: center">Posted</th>
      <th colspan="3" style="text-align: center">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= post.username %></td>
        <td style="text-align: center"><%= post.comments.count %></td>
        <td><%= time_ago_in_words(post.created_at) %> ago</td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, remote: true, :class => 'delete_post' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<%= provide(:page_title, 'New Post') %>

<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%= provide(:page_title, @post.title) %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Author:</strong>
  <%= @post.username %>
  <%= image_tag(@author.avatar.url(:thumb), class: 'img-circle') %>
</p>

<p>
  <strong>Posted:</strong>
  <%= time_ago_in_words(@post.created_at) %> ago
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<br><br>

<p><%= link_to 'Comments', '#', id: 'comments-link' %> <span id="comments-count">(<%= @post.comments.count %>)</span></p>

<section id="comments-section">

<br>

<ol id="comments">
  <%= render @post.comments %>
</ol>

<br>

<%= render "comments/form" %>

</section>